name: Ola Mundo
on: push
jobs:
  saudacao:
    runs-on: ubuntu-latest
    steps:
      - name: Dizer data
        run: date 
      - name: Dizer commit 
        run: echo "Commit feito por ${{ github.actor}}"
