name: Ola Mundo
on: push
jobs:
  saudacao:
    runs-on: ubuntu-latest
    steps:
      - name: Dizer ola
        run: date 
      - name: Dizer bom dia 
        run: echo "estou no quinto ano da Faculdade."
